// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseAntFrom: typeof import('./../src/components/BaseAntFrom.vue')['default']
    BaseDialog: typeof import('./../src/components/BaseDialog.vue')['default']
    BaseElementDropTable: typeof import('./../src/components/table/element/BaseElementDropTable.vue')['default']
    BaseFrom: typeof import('./../src/components/BaseFrom.vue')['default']
    BaseModal: typeof import('./../src/components/BaseModal.vue')['default']
    BasePageSetting: typeof import('./../src/components/BasePageSetting.vue')['default']
    BaseTable: typeof import('./../src/components/table/element/BaseTable.vue')['default']
    BaseTree: typeof import('./../src/components/BaseTree.vue')['default']
    BasicDropEditTable: typeof import('./../src/components/table/ant/BasicDropEditTable.vue')['default']
    BasicDropTreeTable: typeof import('./../src/components/table/ant/BasicDropTreeTable.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    SchemaForm: typeof import('./../src/components/schema-form/schema-form.vue')['default']
    SchemaFormItem: typeof import('./../src/components/schema-form/schema-form-item.vue')['default']
  }
}

export { }
