// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseAntFrom: typeof import('./../src/components/BaseAntFrom.vue')['default']
    BaseDialog: typeof import('./../src/components/BaseDialog.vue')['default']
    BaseFrom: typeof import('./../src/components/BaseFrom.vue')['default']
    BaseModal: typeof import('./../src/components/BaseModal.vue')['default']
    BasePageSetting: typeof import('./../src/components/BasePageSetting.vue')['default']
    BaseTable: typeof import('./../src/components/table/BaseTable.vue')['default']
    BaseTree: typeof import('./../src/components/BaseTree.vue')['default']
    BasicDropEditTable: typeof import('./../src/components/table/BasicDropEditTable.vue')['default']
    BasicDropTreeTable: typeof import('./../src/components/table/BasicDropTreeTable.vue')['default']
    Center: typeof import('./../src/components/visualizationPage/center.vue')['default']
    DiyCenter: typeof import('./../src/components/visualizationPage/diyCenter.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    KonvaCenter: typeof import('./../src/components/visualizationPage/konvaCenter.vue')['default']
    Layouts: typeof import('./../src/components/visualizationPage/layouts.vue')['default']
    Left: typeof import('./../src/components/visualizationPage/left.vue')['default']
    Right: typeof import('./../src/components/visualizationPage/right.vue')['default']
    SchemaForm: typeof import('./../src/components/schema-form/schema-form.vue')['default']
    SchemaFormItem: typeof import('./../src/components/schema-form/schema-form-item.vue')['default']
  }
}

export { }
